import time
nama = input ("Siapa namamu? ")
print ("Halo "+ nama +" , ini cara memasak pasta")
time.sleep(2)
print ("Rebus air")
time.sleep(2)
print ("Tunggu selama 5 menit")
time.sleep(2)
print ("tambahkan pasta")
time.sleep(2)
print("masak selama 10 menit")
time.sleep(2)
print("buang airnya")
time.sleep(2)
print("selesai!")